spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeansimonr2001@gmail.com
    password: wrppukyxikmyaspc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  datasource:
    url: jdbc:postgresql://isabelle.db.elephantsql.com:5432/wziqcptz
    username: wziqcptz
    password: JrApBL51pq1oyip451VcDVOMFR3587YZ
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1200000  # 20 minutos (1200000 milisegundos)
      idle-timeout: 300000    # 5 minutos (300000 milisegundos)
      connection-timeout: 30000  # 30 segundos (30000 milisegundos)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
